enable_ufw_firewall: true

install_packages:
  - postfix
  - unzip
  - libcap2-bin
  - python-is-python3
  - python3-pip

hostname: darkphish
darkphish_user: ubuntu
postfix_hostname: darkphish
postfix_inet_interfaces: 127.0.0.1
darkphish_domain: darkphish.local
darkphish_ssl_cert_path: /etc/ssl/private/darkphish.pem
darkphish_csr_path: /etc/ssl/csr/darkphish.csr
darkphish_crt_path: /etc/ssl/crt/darkphish.crt
# Required if changing /etc/hostname to something different.
reboot_box: true
