package licensing

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"
	"time"
)

// Generated by integrations/wordpress/tests/signer.php in the server PR.
// Only the public key and signed payload are retained, never the test private key.
func TestWordPressSignedLeaseCompatibility(t *testing.T) {
	raw, err := os.ReadFile("testdata/wordpress-v1.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		Envelope       json.RawMessage `json:"envelope"`
		Keyring        KeyringFile     `json:"keyring"`
		Now            int64           `json:"now"`
		InstallationID string          `json:"installation_id"`
	}
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatal(err)
	}
	keys := make(map[string]ed25519.PublicKey)
	for id, value := range fixture.Keyring.Keys {
		key, err := base64.StdEncoding.DecodeString(value)
		if err != nil {
			t.Fatal(err)
		}
		keys[id] = key
	}
	verifier := NewVerifier(keys, 0)
	lease, state, err := verifier.VerifyEnvelope(fixture.Envelope, fixture.InstallationID, time.Unix(fixture.Now, 0))
	if err != nil || state != StateActive || lease.Entitlements.ManagedUsers != 100 || lease.Entitlements.ActiveCampaigns != 1 {
		t.Fatalf("WordPress lease is incompatible: state=%s lease=%+v error=%v", state, lease, err)
	}
	if _, state, err := verifier.VerifyEnvelope(fixture.Envelope, "different-installation", time.Unix(fixture.Now, 0)); err == nil || state != StateInvalid {
		t.Fatal("WordPress lease accepted for a different installation")
	}
}
